name: mlabs_data_engineering_exercise
version: "1.0.0"
config-version: 2

profile: mlabs_data_engineering_exercise

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  mlabs_data_engineering_exercise:
    target_counties:
      +column_types:
        county_fips: VARCHAR
        state_fips: VARCHAR
    raw_census__cd11920_county20:
      +column_types:
        OID_CD119_20: VARCHAR
        GEOID_CD119_20: VARCHAR
        AREALAND_CD119_20: BIGINT
        AREAWATER_CD119_20: BIGINT
        OID_COUNTY_20: VARCHAR
        GEOID_COUNTY_20: VARCHAR
        AREALAND_COUNTY_20: BIGINT
        AREAWATER_COUNTY_20: BIGINT
        AREALAND_PART: BIGINT
        AREAWATER_PART: BIGINT
